### ISSUE TITLE
accuracy.py is not working for overnight dataset

### ISSUE THREAD

**Issue by ayushidalmia** [avikdelta/parse_seq2seq#1]
Is the accuracy code working for overnight?

**Comment by avikdelta** [comment]
@ayushidalmia  It works for a few domains in overnight I tried (e.g. recipe, restaurants). But I am aware that it has some problem in certain overnight domains. As I recall the bug was not too hard to fix. Please feel free to suggest any edit, I will add it.

**Comment by ayushidalmia** [comment]
Ok. Let me check. 

Also, can you please explain what does sort_args method in accuracy.py do?

**Comment by avikdelta** [comment]
There are some logical form predicates like "and:<>", "or:<>", "next_to:<>" which are commutative operators. So the order in which their arguments appear do not matter. For example,

( and:<> arg0 arg1 ) is equivalent to ( and:<> arg1 arg0 )

since both evaluate to the same value. Neural network parsers will often predict a logical form where these arguments are permuted and has a different order than in the ground-truth logical form. But this predicted output is still correct. Hence before checking accuracy by string matching, we sort these arguments in both the ground-truth and the prediction so they have the same order (if correct). The "sort_args" method performs this sorting of the arguments.
